_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x400cdd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0x400d02,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LLLLLLLLLLSS",
    opcodes = "MOV,CMP,MOV,IMUL,MOV,MOV,MOV,IMUL,MOV,MOV,ADD,INC,",
    offsets = "-24,-64,-16,-64,-24,-40,-16,-64,-24,-48,-4,-24,",
    addresses = "0x400d0e,0x400d12,0x400cc6,0x400cca,0x400ccf,0x400cd6,0x400ce3,0x400ce7,0x400cec,0x400cfb,0x400d07,0x400d0a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 92,
    accessed_memory_nooverlap = 44,
    accessed_memory_overlap = 48,
    span = 64,
    head = 0,
    unroll_factor = 1,
  },
}
