_group = {
  {
    group_size = 2,
    pattern = "SS",
    opcodes = "MOV,MOV,",
    offsets = "-1,-1,",
    addresses = "0x2ea5,0x2e38,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 2,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 1,
    span = 1,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 8,
    pattern = "LLLLLLLL",
    opcodes = "MOVZX,MOVZX,MOVZX,MOVZX,MOVZX,MOVZX,MOVZX,MOVZX,",
    offsets = "2,3,0,6,5,1,8,7,",
    addresses = "0x2dc0,0x2dc5,0x2dc9,0x2dcd,0x2de1,0x2de7,0x2df6,0x2dfd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 9,
    head = 0,
    unroll_factor = 1,
  },
}
