_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0x152a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x1502,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LLLLLLLLLLSS",
    opcodes = "MOV,CMP,MOV,IMUL,MOV,MOV,MOV,IMUL,MOV,MOV,ADD,ADD,",
    offsets = "-8,-64,-16,-64,-8,-40,-16,-64,-8,-48,-20,-8,",
    addresses = "0x1537,0x153b,0x14e8,0x14ec,0x14f4,0x14fb,0x1508,0x150c,0x1514,0x1523,0x152f,0x1532,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 92,
    accessed_memory_nooverlap = 44,
    accessed_memory_overlap = 48,
    span = 64,
    head = 0,
    unroll_factor = 1,
  },
}
