_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOV,",
    offsets = "0,",
    addresses = "0x400ad8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x400ab0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LLLLLLLLLLSS",
    opcodes = "MOV,CMP,MOV,IMUL,MOV,MOV,MOV,IMUL,MOV,MOV,ADD,ADD,",
    offsets = "-24,-64,-16,-64,-24,-40,-16,-64,-24,-48,-4,-24,",
    addresses = "0x400ae5,0x400ae9,0x400a96,0x400a9a,0x400aa2,0x400aa9,0x400ab6,0x400aba,0x400ac2,0x400ad1,0x400add,0x400ae0,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 92,
    accessed_memory_nooverlap = 44,
    accessed_memory_overlap = 48,
    span = 64,
    head = 0,
    unroll_factor = 1,
  },
}
