_group = {
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOV,MOV,",
    offsets = "0,0,",
    addresses = "0x2a62,0x2a6e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "LS",
    opcodes = "MOV,MOV,",
    offsets = "0,0,",
    addresses = "0x2a4b,0x2a57,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 8,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 12,
    pattern = "LSLSLSLSLSLS",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "0,0,0,0,0,0,0,0,0,0,0,0,",
    addresses = "0x2a79,0x2a85,0x2a90,0x2a9c,0x2aa7,0x2ab3,0x2abe,0x2aca,0x2ad5,0x2ae1,0x2aec,0x2af8,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 96,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 88,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 16,
    pattern = "LSLSLSLSLSLSLSLS",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,",
    addresses = "0x2a48,0x2a54,0x2a5b,0x2a6b,0x2a72,0x2a82,0x2a89,0x2a99,0x2aa0,0x2ab0,0x2ab7,0x2ac7,0x2ace,0x2ade,0x2ae5,0x2af5,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 120,
    span = 8,
    head = 0,
    unroll_factor = 1,
  },
}
