_group = {
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x20b3,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x20e9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 8,
    pattern = "LLLSLLLL",
    opcodes = "MOV,MOV,MOV,MOV,MOV,ADD,CMP,CMP,",
    offsets = "152,144,136,64,32,64,160,160,",
    addresses = "0x2083,0x2093,0x209f,0x20db,0x20df,0x2101,0x222c,0x210e,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 56,
    accessed_memory_nooverlap = 44,
    accessed_memory_overlap = 12,
    span = 136,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 2,
    pattern = "SS",
    opcodes = "MOV,MOV,",
    offsets = "0,0,",
    addresses = "0x2228,0x211a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 2,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 1,
    span = 1,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x20a7,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 3,
    pattern = "LLL",
    opcodes = "MOVZX,MOVZX,MOVZX,",
    offsets = "0,0,0,",
    addresses = "0x20ac,0x20b7,0x20e4,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 3,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 2,
    span = 1,
    head = 0,
    unroll_factor = 3,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x208f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "MOVZX,",
    offsets = "0,",
    addresses = "0x209b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 1,
    accessed_memory_nooverlap = 1,
    accessed_memory_overlap = 0,
    span = 1,
    head = 0,
    unroll_factor = 1,
  },
}
